version: '3'

volumes:
 data:
 config:
 db:

services:
 nextcloud-db:
  image: mariadb
  container_name: nextcloud-db
  restart: always
  volumes:
   - ./db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=Admin123!
   - MYSQL_PASSWORD=nextcloud
   - MYSQL_DATABASE=nextcloud
   - MYSQL_USER=nextcloud
 nextcloud:
  image: nextcloud
  container_name: nextcloud
  restart: always
  ports:
   - 8080:80
  depends_on:
   - nextcloud-db
  volumes:
   - ./config:/var/www/html/config
   - /nextcloud-data:/var/www/html/data
   - ./apps:/var/www/html/apps
   - ./custom_apps:/var/www/html/custom_apps
    